// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <rtthread.h>
#include "hal_data.h"
#include <rtdevice.h>
#include <rtdbg.h>
#include <errno.h>
extern rt_device_t u4_dev;
uint8_t mode_flag = 0;
void defects_callback(lv_event_t * e)
{
	// Your code here
    rt_device_write(u4_dev, 0, "1\n", rt_strlen("1\n"));
    mode_flag = 1;

}

void size_callback(lv_event_t * e)
{
	// Your code here
    rt_device_write(u4_dev, 0, "2\n", rt_strlen("2\n"));
    mode_flag = 2;
}

void default_callback(lv_event_t * e)
{
	// Your code here
    rt_device_write(u4_dev, 0, "0\n", rt_strlen("0\n"));
    mode_flag = 0;
}
