// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME2_H
#define UI_HOME2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home2
extern void ui_home2_screen_init(void);
extern void ui_home2_screen_destroy(void);
extern lv_obj_t * ui_home2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label15;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

