// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME1_H
#define UI_HOME1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home1
extern void ui_home1_screen_init(void);
extern void ui_home1_screen_destroy(void);
extern lv_obj_t * ui_home1;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

